[env]
RUST_TEST_THREADS = "1"     # prevent running multiple RouDiEnvironments in parallel with `cargo test`
NEXTEST_TEST_THREADS = "1"  # prevent running multiple RouDiEnvironments in parallel with `cargo nextest run`
