name: Rust Linting & Code Formatting

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-format-check:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt clippy
            override: true
      - name: Check Formatting
        run: |
          cargo clippy
          cargo fmt --check

