name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-flight-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --check

  build-test:
    needs: pre-flight-check
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] #Todo add windows-latest
        toolchain: [stable, beta]
        include:
        - os: ubuntu-latest
          toolchain: nightly

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain != 'stable' }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: clippy
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cache-${{ runner.os }}-toolchain-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/build.rs') }}
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install -y libacl1-dev libncurses5-dev
        fi
        cargo-nextest --version > /dev/null || cargo install cargo-nextest --locked
    - name: Build
      run: cargo build --all --examples
    - if: runner.os == 'Linux' && matrix.toolchain == 'stable'
      name: Run clippy # clippy can reuse the previous build artifacts
      run: cargo clippy
    - name: Run tests
      run: cargo nextest run --test-threads 1

  coverage:
    needs: pre-flight-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        components: llvm-tools-preview
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: coverage-llvm-tools-preview-cache-${{ runner.os }}-toolchain-nightly-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/build.rs') }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libacl1-dev libncurses5-dev
        cargo-nextest --version > /dev/null || cargo install cargo-nextest --locked
        grcov --version > /dev/null || cargo install grcov
    - name: Build
      env:
        RUSTFLAGS: -Cinstrument-coverage
      run: cargo build
    - name: Run test
      env:
        LLVM_PROFILE_FILE: target/debug/llvm-profile-files/iceoryx-rs-%p-%m.profraw
        RUSTFLAGS: -Cinstrument-coverage
      run: cargo nextest run --test-threads 1
    - name: Generate coverage results for html artifacts
      run: |
        grcov target/debug/llvm-profile-files   \
          --binary-path target/debug            \
          --source-dir .                        \
          --output-type html                    \
          --branch                              \
          --ignore-not-existing                 \
          --ignore build.rs                     \
          --ignore "examples/*"                 \
          --ignore "src/testing/*"              \
          --ignore "src/tests/*"                \
          --output-path target/debug/coverage-html
        sed -i 's/coverage/grcov/' target/debug/coverage-html/coverage.json
    - name: Archive coverage-html artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: target/debug/coverage-html/*
        retention-days: 00
    - name: Generate coverage report for Codecov
      run: |
        grcov target/debug/llvm-profile-files   \
          --binary-path target/debug            \
          --source-dir .                        \
          --output-type lcov                    \
          --branch                              \
          --ignore-not-existing                 \
          --ignore build.rs                     \
          --ignore "examples/*"                 \
          --ignore "src/testing/*"              \
          --ignore "src/tests/*"                \
          --output-path target/debug/lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: target/debug/lcov.info
        fail_ci_if_error: true
